stages:
  - build
  - push
  - deploy

build:
  stage: build
  image: java:8-jdk-alpine
  before_script:
    - apk update
    - apk add bash build-base
  script:
    - ./scripts/build.sh
  artifacts:
    paths:
      - build/libs
push:
  stage: push
  image: docker:1.11.2
  dependencies:
    - build
  tags:
      - docker
  before_script:
    - apk update
    - apk add bash
    - export DOCKER_HOST="tcp://106.186.112.244:2375"
    - docker login -u liu-jerry -p lzy4361814 registry.gitlab.com
  script:
    - ./scripts/push.sh

# deploy:
#   stage: deploy
#   image: docker:1.11.2
#   before_script:
#       - apk update
#       - apk add bash
#       - export DOCKER_HOST="tcp://106.186.112.244:2395"
#       - docker login -u liu-jerry -p lzy4361814 registry.gitlab.com
#   script:
#     - ./scripts/deploy.sh