server:
  port: ${PORT:8083}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

zuul:
  routes:
    user-center: /orders/**
    order-center: /users/**

